### ISSUE TITLE
Mac version still 0.19

### ISSUE THREAD

**Issue by badvision** [djyt/cannonball#11]
The Mac binary is not up-to-date and crashes when you try to use Japan tracks.  Are there tips on how to build mac binaries from the current source?

**Comment by superandroidtron** [comment]
First, you'll need to get SDL. This can easily be done through homebrew or macports.
Due to a boost API change, you'll need to edit frontend/config.cpp and change all instances of
```c++
boost::property_tree::xml_writer_settings<char> settings ('\t', 1);
```
to
```c++
auto settings = boost::property_tree::xml_writer_make_settings<std::string> ('\t', 1);
```
source: http://www.pcl-users.org/problem-getting-PCL-1-7-1-on-osx-10-9-td4035213.html
Then, when configuring your makefile with cmake, make sure to pass it your sysroot. I had trouble passing the TARGET argument, so I just changed the default target to macosx.  That should be all you'll need to do. Roms should be stored in a folder called "roms" in the same directory as the executable.

**Comment by badvision** [comment]
Thanks!  Yeah that is basically what I had to do, but I did manage to get
it working as well.  Is the master branch going to be updated to reflect
the boost API change or should this sort of thing be maintained in a fork
for the newer Boost library?

**Comment by superandroidtron** [comment]
Some preprocessor directives might be the best option in order to maintain compatibility with both the old and new boost APIs.

**Comment by gingerbeardman** [comment]
Any chance of a binary release of a current macOS port? Thanks!

**Comment by djyt** [comment]
I don't maintain the Mac port unfortunately. But anyone is welcome to create one from the latest source code.
