### ISSUE TITLE
Full screen mode is broken at 3840x2160

### ISSUE THREAD

**Issue by gameuser1982** [djyt/cannonball#50]
I'm running at 3840x2160 and although cannon ball works perfectly in a window, it's totally non functional for full screen mode. When I set it to full screen, it blows up 25% of the screen to full screen with the rest of the screen cut off at my monitor's borders. This makes it impossible to play the game full screen.

**Comment by carstene1ns** [comment]
Do you have any High-DPI / retina setup? Are you using SDL1 or SDL2? Also, operating system?

**Comment by gameuser1982** [comment]
If by high DPI / retina you mean scaling my fonts in Windows, I do do that. I scale them 200%
 
I am not sure which version of SDL. I simply downloaded the cannon ball software and extradited the rom into it.
 
Operating system is windows 10 pro.

In 1920x1080 resolution full screen mode works perfectly so it definitely has a problem with my native 4k resolution.

**Comment by redesigndev** [comment]
This issue is fixed by changing the 'High DPI Settings' of cannonball.exe
![Properties > Compatibility Pane](https://user-images.githubusercontent.com/56522308/82692867-53a83400-9c15-11ea-9710-066fee94a07d.png)
![Hi DPI Override](https://user-images.githubusercontent.com/56522308/82693060-a84baf00-9c15-11ea-85da-b91650e1e41d.png)
Changing this setting solves the scaling issue, and let's you play the game in native 4K.

**Comment by djyt** [comment]
Can anyone confirm whether this is still an issue on the latest SDL2 based build? I don't have a 4k monitor, but I would be interested to know.

**Comment by redesigndev** [comment]
It doesn't seem to be an issue anymore on my setup.

**Comment by djyt** [comment]
OK great. Must have been a result of SDL 1 being ancient technology. I'll close this for now. Thank you!
