### ISSUE TITLE
Cannonball doesn't run on Windows 10

### ISSUE THREAD

**Issue by Roareye** [djyt/cannonball#58]
Whether I open the program via Steam or via the App directly, no matter whether I launch it in compatibility mode or not (Tried Windows 8, Windows Vista, Windows 7, XP... no joy) this game refuses to load. It will load the black and white code window and then just disappear never to be seen again.

Anyone know how to make this work on a PC? XD

**Comment by MichaelRPowell** [comment]
Just to confirm, did you add the required additional files not included in the install?

**Comment by Roareye** [comment]
Do I need to add the Arcade ROMS in? I thought this was a rebuild via C++, not an emulator.
If they're not ROMs I don't understand why they're not in the install process. There's no How To to install this game, so I thought it would be simple >_>

**Comment by MichaelRPowell** [comment]
The ROM is needed. A second ROM is needed if you want the additional track. Check the 'roms' folder and read the 'roms.txt' file for the details.

This engine does not have visual or audio assets included (those are protected by copyright). It uses them from the ROM file(s).

If you have any other issues I will try to help!

**Comment by MichaelRPowell** [comment]
> There's no How To to install this game

Clicking the Wiki tab, or you can follow [this direct link](https://github.com/djyt/cannonball/wiki/Cannonball-Manual), will take you to the manual and setup directions.

On that page it lists under "Getting Started" step 2:
> You will need the OutRun Revision B ROMs. They must be named correctly and uncompressed to the roms subdirectory.
Most problems arise from incorrect ROM naming. roms.txt specifies exactly what you need.
You can optionally add the Japanese ROMS for additional courses (found in the outruno set).

I hope this clarifies everything so that this issue can be marked closed!

**Comment by djyt** [comment]
Thanks Michael.
