### ISSUE TITLE
Bend before s-bend stage 1, no drifting

### ISSUE THREAD

**Issue by steviebferrari** [djyt/cannonball#71]

**Comment by steviebferrari** [comment]
The car at full speed usually driffts wide and smoke comes from wheels, but goes round corner too easily

**Comment by djyt** [comment]
I'm not sure I can reproduce this. I've played on MAME and CannonBall on the same controller and the handling seems identical.

Depending on how your controller is calibrated it may well be easier than on the arcade cab, as a small analog thumbstick is a lot more responsive than turning a big wheel. The Saturn version is noticeable much easier than the arcade version for this reason also, but there's no underlying difference in the code.

**Comment by steviebferrari** [comment]
Does it on keyboard too

Steve

**Comment by djyt** [comment]
Yes, but a lot of this is down to the way in which the analog wheel is simulated using digital controls. If you turn down the digital steer speed, you'll find it's more difficult to take the corner.

You can take this corner at full speed on arcade hardware if you get your line correct. What are you comparing this with exactly? I need more information to look into the problem - a video, details on your control settings etc. Otherwise, I have nothing to work from.

**Comment by steviebferrari** [comment]
thank you very much for your replies,  it looks so good on a wide screen
tv, amazing work :)
